# Generated by Django 3.2 on 2023-08-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_instrucao', models.CharField(choices=[('S', 'Superior Completo'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='S', max_length=1)),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
    ]
